// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ProductionOrderSEQUOR.API.Models
{
    public partial class ControleProductionOrderContext : DbContext
    {
        public ControleProductionOrderContext()
        {
        }

        public ControleProductionOrderContext(DbContextOptions<ControleProductionOrderContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductMaterial> ProductMaterial { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Material>(entity =>
            {
                entity.HasKey(e => e.MaterialCode)
                    .HasName("PK__Material__170C54BBBD61999C");
            });

            modelBuilder.Entity<Order>(entity =>
            {
                entity.HasKey(e => e.Order1)
                    .HasName("PK__Order__67A3D86D6DCFC611");
            });

            modelBuilder.Entity<Product>(entity =>
            {
                entity.HasKey(e => e.ProductCode)
                    .HasName("PK__Product__2F4E024EF16DAE3E");
            });

            modelBuilder.Entity<ProductMaterial>(entity =>
            {
                entity.HasKey(e => new { e.ProductCode, e.MaterialCode })
                    .HasName("PK__ProductM__8E3EC7058AC94BB1");

                entity.HasOne(d => d.MaterialCodeNavigation)
                    .WithMany(p => p.ProductMaterial)
                    .HasForeignKey(d => d.MaterialCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ProductMa__Mater__2B3F6F97");

                entity.HasOne(d => d.ProductCodeNavigation)
                    .WithMany(p => p.ProductMaterial)
                    .HasForeignKey(d => d.ProductCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ProductMa__Produ__2A4B4B5E");
            });

            modelBuilder.Entity<Usuario>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}