// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ProductionOrderSEQUOR.API.Models
{
    public partial class ControleProductionOrderContext : DbContext
    {
        public ControleProductionOrderContext()
        {
        }

        public ControleProductionOrderContext(DbContextOptions<ControleProductionOrderContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductMaterial> ProductMaterial { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Material>(entity =>
            {
                entity.HasKey(e => e.MaterialCode)
                    .HasName("PK__Material__170C54BBBD61999C");

                entity.Property(e => e.IdMaterial).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<Order>(entity =>
            {
                entity.HasKey(e => e.Order1)
                    .HasName("PK__Order__67A3D86D6DCFC611");

                entity.Property(e => e.IdOrder).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<Product>(entity =>
            {
                entity.HasKey(e => e.ProductCode)
                    .HasName("PK__Product__2F4E024EF16DAE3E");

                entity.Property(e => e.IdProduct).ValueGeneratedOnAdd();

                entity.HasOne(d => d.ProductCodeNavigation)
                    .WithOne(p => p.Product)
                    .HasForeignKey<Product>(d => d.ProductCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Product_Material");
            });

            modelBuilder.Entity<ProductMaterial>(entity =>
            {
                entity.HasKey(e => new { e.ProductCode, e.MaterialCode })
                    .HasName("PK__ProductM__8E3EC7058AC94BB1");

                entity.Property(e => e.IdMaterial).ValueGeneratedOnAdd();

                entity.HasOne(d => d.MaterialCodeNavigation)
                    .WithMany(p => p.ProductMaterial)
                    .HasForeignKey(d => d.MaterialCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ProductMa__Mater__2B3F6F97");

                entity.HasOne(d => d.ProductCodeNavigation)
                    .WithMany(p => p.ProductMaterial)
                    .HasForeignKey(d => d.ProductCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ProductMa__Produ__2A4B4B5E");
            });

            modelBuilder.Entity<Production>(entity =>
            {
                entity.HasKey(e => e.IdProduction)
                    .HasName("PK__Producti__3213E83F8837020F");

                entity.HasOne(d => d.idNavigation)
                    .WithMany(p => p.Production)
                    .HasPrincipalKey(p => p.Email)
                    .HasForeignKey(d => d.Email)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Productio__Email__30F848ED");

                entity.HasOne(d => d.MaterialCodeNavigation)
                    .WithMany(p => p.Production)
                    .HasForeignKey(d => d.MaterialCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Productio__Mater__32E0915F");

                entity.HasOne(d => d.OrderNavigation)
                    .WithMany(p => p.Production)
                    .HasForeignKey(d => d.Order)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Productio__Order__31EC6D26");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}