// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductionOrderSEQUOR.API.Models
{
    public partial class Order
    {
        [Key]
        [Column("Order")]
        [StringLength(50)]
        [Unicode(false)]
        public string Order1 { get; set; }
        [Column("id")]
        public int Id { get; set; }
        [Column("OrderID")]
        public int OrderId { get; set; }
    }
}