// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductionOrderSEQUOR.API.Models
{
    public partial class ProductMaterial
    {
        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string ProductCode { get; set; }
        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string MaterialCode { get; set; }
        [Column("idMaterial")]
        public int IdMaterial { get; set; }

        [ForeignKey("MaterialCode")]
        [InverseProperty("ProductMaterial")]
        public virtual Material MaterialCodeNavigation { get; set; }
        [ForeignKey("ProductCode")]
        [InverseProperty("ProductMaterial")]
        public virtual Product ProductCodeNavigation { get; set; }
    }
}