// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductionOrderSEQUOR.API.Models
{
    public partial class Production
    {
        [Key]
        [Column("ID")]
        public long Id { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [Column("OrderID")]
        [StringLength(50)]
        [Unicode(false)]
        public string OrderId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal Quantity { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string MaterialCode { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal CycleTime { get; set; }

        [ForeignKey("Email")]
        [InverseProperty("Production")]
        public virtual User EmailNavigation { get; set; }
        [ForeignKey("OrderId")]
        [InverseProperty("Production")]
        public virtual Order Order { get; set; }
    }
}