// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductionOrderSEQUOR.API.Models
{
    public partial class Product
    {
        public Product()
        {
            ProductMaterial = new HashSet<ProductMaterial>();
        }

        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string ProductCode { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string ProductDescription { get; set; }
        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string Image { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal CycleTime { get; set; }
        [Column("idProduct")]
        public int IdProduct { get; set; }

        [ForeignKey("ProductCode")]
        [InverseProperty("Product")]
        public virtual Material ProductCodeNavigation { get; set; }
        [InverseProperty("ProductCodeNavigation")]
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}