// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
// using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace ProductionOrderSEQUOR.API.Models
{
    [Index("Email", Name = "UQ__User__A9D1053455A341B6", IsUnique = true)]
    public partial class User
    {
        public User()
        {
            Production = new HashSet<Production>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Email { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? InitialDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }

        public virtual ICollection<Production> Production { get; set; }
       // public ClaimsIdentity UserName { get; internal set; }
    }
}