// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductionOrderSEQUOR.API.Models
{
    public partial class User
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("CPF")]
        [StringLength(11)]
        [Unicode(false)]
        public string Cpf { get; set; }
    }
}