// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductionOrderSEQUOR.API.Models
{
    public partial class Usuario
    {
        [Key]
        [Column("idUsuario")]
        public int IdUsuario { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(250)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [StringLength(3)]
        [Unicode(false)]
        public string Username { get; set; }
        [Required]
        [Column("passwordHash")]
        public byte[] PasswordHash { get; set; }
        [Required]
        [Column("passwordSalt")]
        public byte[] PasswordSalt { get; set; }
    }
}